-- RoRota Default Profile Module
-- Default profile configuration for new characters

RoRotaDefaultProfile = {
	abilities = {
		SliceAndDice = {enabled = true, minCP = 1, maxCP = 2, targetMinHP = 10, targetMaxHP = 100, targetMinHPFlat = 0, targetMaxHPFlat = 9999999, onlyElites = false},
		Eviscerate = {enabled = true, targetMinHP = 0, targetMaxHP = 100, targetMinHPFlat = 0, targetMaxHPFlat = 9999999, onlyElites = false, smartEviscerate = true, useColdBlood = false, coldBloodMinCP = 4},
		SinisterStrike = {enabled = true},
		NoxiousAssault = {enabled = false},
		Envenom = {enabled = false, minCP = 1, maxCP = 2, targetMinHP = 10, targetMaxHP = 100, targetMinHPFlat = 0, targetMaxHPFlat = 9999999, onlyElites = false},
		Rupture = {enabled = false, minCP = 1, maxCP = 5, targetMinHP = 15, targetMaxHP = 100, targetMinHPFlat = 0, targetMaxHPFlat = 9999999, onlyElites = false},
		ExposeArmor = {enabled = false, minCP = 5, maxCP = 5, targetMinHP = 0, targetMaxHP = 100, targetMinHPFlat = 0, targetMaxHPFlat = 9999999, onlyElites = false},
		ColdBloodEviscerate = {enabled = false, minCP = 4, maxCP = 5, targetMinHP = 0, targetMaxHP = 100, targetMinHPFlat = 0, targetMaxHPFlat = 9999999, onlyElites = false},
		ShadowOfDeath = {enabled = false, minCP = 5, maxCP = 5, targetMinHP = 0, targetMaxHP = 100, targetMinHPFlat = 0, targetMaxHPFlat = 9999999, onlyElites = false},
		MarkForDeath = {enabled = false, targetMinHP = 0, targetMaxHP = 100, targetMinHPFlat = 0, targetMaxHPFlat = 9999999, onlyElites = false},
		Hemorrhage = {enabled = false, targetMinHP = 0, targetMaxHP = 100, targetMinHPFlat = 0, targetMaxHPFlat = 9999999, onlyElites = false, onlyWhenMissing = false},
		Backstab = {enabled = false, failsafeAttempts = 3},
	},
	mainBuilder = "Sinister Strike",
	secondaryBuilder = "Sinister Strike",
	builderFailsafe = 3,
	smartBuilders = false,
	buffPriority = "Slice and Dice",
	opener = {
		ability = "Ambush",
		secondaryAbility = "Sinister Strike",
		failsafeAttempts = 3,
		pickPocket = false,
		sapFailAction = "None",
	},
	interrupt = {
		useKick = true,
		useGouge = false,
		useKidneyShot = false,
		kidneyMaxCP = 2,
	},
	finisherPriority = {"Slice and Dice", "Rupture", "Envenom", "Expose Armor", "Cold Blood Eviscerate"},
	smartRupture = true,
	energyPooling = {
		enabled = true,
		threshold = 10,
	},
	finisherRefreshThreshold = 2,  -- refresh finishers when <= X seconds remaining (0-3s)
	previewDepth = 1,  -- show 1-3 abilities in preview window
	defensive = {
		useVanish = false,
		vanishHP = 20,
		useGhostlyStrike = false,
		ghostlyTargetMaxHP = 30,
		ghostlyPlayerMinHP = 1,
		ghostlyPlayerMaxHP = 90,
		useFeint = false,
		feintMode = "Always",
		useRiposte = false,
		riposteTargetMinHP = 0,
		riposteTargetMaxHP = 100,
		useSurpriseAttack = false,
		surpriseTargetMinHP = 0,
		surpriseTargetMaxHP = 100,
	},
	poisons = {
		enabled = true,
		timeThreshold = 180,
		chargesThreshold = 10,
		autoApply = false,
		applyInCombat = false,
		mainHandPoison = "None",
		offHandPoison = "None",
	},
}
